package com.socrata.http.server.ext

case class StatusCode(code: Int)

object StatusCode {
  val OK = StatusCode(200)
  val Created = StatusCode(201)
  val Accepted = StatusCode(202)
  val NonAuthoritative = StatusCode(203)
  val NoContent = StatusCode(204)
  val ResetContent = StatusCode(205)
  val PartialContent = StatusCode(206)

  val MultipleChoices = StatusCode(300)
  val MovedPermanently = StatusCode(301)
  val Found = StatusCode(302)
  val SeeOther = StatusCode(303)
  val NotModified = StatusCode(304)
  val TemporaryRedirect = StatusCode(307)
  val PermanentRedirect = StatusCode(308)

  val BadRequest = StatusCode(400)
  val Unauthorized = StatusCode(401)
  val Forbidden = StatusCode(403)
  val NotFound = StatusCode(404)
  val MethodNotAllowed = StatusCode(405)
  val NotAcceptable = StatusCode(406)
  val ProxyAuthenticationRequired = StatusCode(407)
  val RequestTimeout = StatusCode(408)
  val Conflict = StatusCode(409)
  val Gone = StatusCode(410)
  val LengthRequired = StatusCode(411)
  val PreconditionFailed = StatusCode(412)
  val PayloadTooLarge = StatusCode(413)
  val URITooLong = StatusCode(414)
  val UnsupportedMediaType = StatusCode(415)
  val RangeNotSatisfiable = StatusCode(416)
  val ExpectationFailed = StatusCode(417)
  val ImATeapot = StatusCode(418)
  val MisdirectedRequest = StatusCode(421)
  val UpgradeRequired = StatusCode(426)
  val PreconditionRequired = StatusCode(428)
  val TooManyRequests = StatusCode(429)
  val RequestHeaderFieldsTooLarge = StatusCode(431)
  val UnavailableForLegalReasons = StatusCode(451)

  val InternalServerError = StatusCode(500)
  val NotImplemented = StatusCode(501)
  val BadGateway = StatusCode(502)
  val ServiceUnavailable = StatusCode(503)
  val GatewayTimeout = StatusCode(504)
  val HTTPVersionNotSupported = StatusCode(505)
  val VariantAlsoNegiotiates = StatusCode(506)
  val NotExtended = StatusCode(510)
  val NetworkAuthenticationRequired = StatusCode(511)
}
